# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=800)),
                ('data', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
