# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
