# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20171208_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
